<?php

declare(strict_types=1);

namespace BlackOps\Internal\Aop\FrameworkProxyContract;

final class FrameworkProxyDiagnosticCode
{
    public const SIGNATURE_FINAL_CLASS = 'BO_PROXY_SIGNATURE_FINAL_CLASS';
    public const SIGNATURE_FINAL_METHOD = 'BO_PROXY_SIGNATURE_FINAL_METHOD';
    public const SIGNATURE_VISIBILITY = 'BO_PROXY_SIGNATURE_VISIBILITY';
    public const SIGNATURE_STATIC = 'BO_PROXY_SIGNATURE_STATIC';
    public const SIGNATURE_GENERATOR = 'BO_PROXY_SIGNATURE_GENERATOR';
    public const SIGNATURE_REFERENCE_RETURN = 'BO_PROXY_SIGNATURE_REFERENCE_RETURN';
    public const SIGNATURE_REFERENCE_PARAMETER = 'BO_PROXY_SIGNATURE_REFERENCE_PARAMETER';
    public const SIGNATURE_AFTER_COMMIT_RETURN = 'BO_PROXY_SIGNATURE_AFTER_COMMIT_RETURN';
    public const SIGNATURE_DEFAULT_VALUE = 'BO_PROXY_SIGNATURE_DEFAULT_VALUE';
    public const ATTRIBUTE_CONFLICT = 'BO_PROXY_ATTRIBUTE_CONFLICT';
    public const ATTRIBUTE_TARGET = 'BO_PROXY_ATTRIBUTE_TARGET';
    public const ATTRIBUTE_DUPLICATE = 'BO_PROXY_ATTRIBUTE_DUPLICATE';
    public const TARGET_NOT_CONCRETE = 'BO_PROXY_TARGET_NOT_CONCRETE';
    public const DEFINITION_FACTORY = 'BO_PROXY_DEFINITION_FACTORY';
    public const DEFINITION_LAZY = 'BO_PROXY_DEFINITION_LAZY';
    public const DEFINITION_SYNTHETIC = 'BO_PROXY_DEFINITION_SYNTHETIC';
    public const DEFINITION_ABSTRACT = 'BO_PROXY_DEFINITION_ABSTRACT';
    public const DEFINITION_DECORATION = 'BO_PROXY_DEFINITION_DECORATION';
    public const CONNECTION_UNKNOWN = 'BO_PROXY_CONNECTION_UNKNOWN';
    public const MODE_CONFLICT = 'BO_PROXY_MODE_CONFLICT';
    public const OWNERSHIP_CONFLICT = 'BO_PROXY_OWNERSHIP_CONFLICT';

    private function __construct() {}
}
