<?php

declare(strict_types=1);

namespace BlackOps\Internal\Aop\FrameworkProxyArtifact;

final class FrameworkProxyArtifactDiagnosticCode
{
    public const MANIFEST_INVALID = 'BO_PROXY_ARTIFACT_MANIFEST_INVALID';
    public const MANIFEST_HASH = 'BO_PROXY_ARTIFACT_MANIFEST_HASH';
    public const BUILD_MISMATCH = 'BO_PROXY_ARTIFACT_BUILD_MISMATCH';
    public const PROFILE_MISMATCH = 'BO_PROXY_ARTIFACT_PROFILE_MISMATCH';
    public const FILE_HASH = 'BO_PROXY_ARTIFACT_FILE_HASH';
    public const MAP_MISMATCH = 'BO_PROXY_ARTIFACT_MAP_MISMATCH';
    public const VERSION_MISMATCH = 'BO_PROXY_ARTIFACT_VERSION_MISMATCH';
    public const GENERATED_MEMBER_COLLISION = 'BO_PROXY_GENERATED_MEMBER_COLLISION';
    public const SYNTAX_INVALID = 'BO_PROXY_ARTIFACT_SYNTAX_INVALID';
    public const SOURCE_UNAVAILABLE = 'BO_PROXY_ARTIFACT_SOURCE_UNAVAILABLE';
    public const SOURCE_HASH = 'BO_PROXY_ARTIFACT_SOURCE_HASH';
    public const DUPLICATE_IDENTITY = 'BO_PROXY_ARTIFACT_DUPLICATE_IDENTITY';
    public const IDENTITY_INCONSISTENT = 'BO_PROXY_ARTIFACT_IDENTITY_INCONSISTENT';
    public const CLASS_MISMATCH = 'BO_PROXY_ARTIFACT_CLASS_MISMATCH';
    public const HASH_VERIFICATION = 'BO_PROXY_ARTIFACT_HASH_VERIFICATION';
    public const INPUT_INVALID = 'BO_PROXY_ARTIFACT_INPUT_INVALID';
    public const BUILD_ID_INVALID = 'BO_PROXY_ARTIFACT_BUILD_ID_INVALID';
    public const DIRECTORY_IO = 'BO_PROXY_ARTIFACT_DIRECTORY_IO';
    public const WRITE_IO = 'BO_PROXY_ARTIFACT_WRITE_IO';
    public const PUBLISH_IO = 'BO_PROXY_ARTIFACT_PUBLISH_IO';
    public const INDEX_INVALID = 'BO_PROXY_ARTIFACT_INDEX_INVALID';
    public const GENERATION_INVALID = 'BO_PROXY_ARTIFACT_GENERATION_INVALID';
}
